version: '3'

services:
  core:
    image: core_image
    build: .
    volumes:
      - .:/app
  tests:
    image: core_image
    build:
      dockerfile: Dockerfile-test
      context: .
    command: bash -c "prospector && coverage run --source='.' && coverage report"
    volumes:
      - .:/app
  ubuntu:
    build:
      dockerfile: Dockerfile-ubuntu
      context: .
